"use client";

/* Signed and local previews intentionally use a native image element. */
/* eslint-disable @next/next/no-img-element */

import { useCallback, useEffect, useRef, useState, type ClipboardEvent } from "react";
import { listProductTemplateSubgroupReferences, removeProductTemplateSubgroupReference, saveProductTemplateSubgroupReference } from "@/app/products/templates/subgroup-reference-actions";
import { usePendingSubgroupReference } from "@/components/products/pending-subgroup-reference-context";
import { clipboardImageFile, compressedClipboardImage } from "@/lib/products/product-template-row-image-client";
import type { ProductTemplateSubgroupReferencePreview } from "@/lib/products/product-template-subgroup-references";
import type { ProductTemplateGroupReferenceType } from "@/lib/products/product-template-group-references";

export function PricingSubgroupReferenceImage({ groupId, pricingType = "base_model", subgroupId, templateId, templateIsPersisted }: { groupId: string; pricingType?: ProductTemplateGroupReferenceType; subgroupId: string; templateId: string; templateIsPersisted: boolean }) {
  const pending = usePendingSubgroupReference(pricingType, groupId, subgroupId); const targetRef = useRef<HTMLDivElement>(null); const [reference, setReference] = useState<ProductTemplateSubgroupReferencePreview | null>(null); const [message, setMessage] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { if (!templateIsPersisted) return; try { const rows = await listProductTemplateSubgroupReferences(templateId, { pricingType, groupId, subgroupId }); setReference(rows[0] ?? null); } catch { setMessage("Reference image could not be loaded."); } }, [groupId, pricingType, subgroupId, templateId, templateIsPersisted]);
  useEffect(() => { const target = targetRef.current; if (!target || !templateIsPersisted) return; const observer = new IntersectionObserver((entries) => { if (entries.some((entry) => entry.isIntersecting)) { void load(); observer.disconnect(); } }); observer.observe(target); return () => observer.disconnect(); }, [load, templateIsPersisted]);
  const paste = async (event: ClipboardEvent<HTMLDivElement>) => { const clipboardFile = clipboardImageFile(event.clipboardData.files); if (!clipboardFile) { setMessage("Clipboard does not contain an image."); return; } event.preventDefault(); if (!templateIsPersisted && !pending) { setMessage("Save the Product Template before adding subgroup images."); return; } setBusy(true); setMessage(null); try { const file = await compressedClipboardImage(clipboardFile); if (pending) pending.replace(file, URL.createObjectURL(file)); else setReference(await saveProductTemplateSubgroupReference({ templateId, pricingType, groupId, subgroupId, file })); } catch (error) { setMessage(error instanceof Error ? error.message : "Reference image could not be saved."); } finally { setBusy(false); } };
  const remove = async () => { if (!reference) return; setBusy(true); try { await removeProductTemplateSubgroupReference(reference.id); setReference(null); } catch { setMessage("Reference image could not be removed."); } finally { setBusy(false); } };
  const preview = pending?.image?.previewUrl ?? reference?.previewUrl;
  return <div className="w-[76px]" ref={targetRef}><div tabIndex={0} onPaste={paste} title="Focus and press Ctrl+V to paste a subgroup diagram" className="flex h-16 w-16 items-center justify-center overflow-hidden rounded-md border border-dashed border-zinc-300 bg-zinc-50 text-center text-[10px] leading-3 text-zinc-500 outline-none focus:border-emerald-700 focus:ring-2 focus:ring-emerald-100">{preview ? <img src={preview} alt="Subgroup reference" className="h-full w-full object-contain" loading="lazy" /> : busy ? "Saving..." : <>Paste image<br />Ctrl+V</>}</div>{pending?.image ? <><p className="mt-1 text-[9px] text-amber-700">Pending save</p><button type="button" onClick={pending.remove} className="text-[10px] font-semibold text-red-700">Remove</button></> : reference ? <><p className="mt-1 text-[9px] text-zinc-500">Paste to replace</p><button type="button" disabled={busy} onClick={remove} className="text-[10px] font-semibold text-red-700">Remove</button></> : null}{message ? <p className="mt-1 text-[9px] leading-3 text-amber-800">{message}</p> : null}</div>;
}
