"use client";
import { useEffect, useMemo, useState } from "react";
import { runSourceQaAi } from "@/app/products/templates/source-qa-actions";
import { SourceQaCropViewer } from "@/components/products/source-qa-crop-viewer";
import { analyzeSourcePdf, primarySourceQaFindings, sourceQaReviewStatus, type SourceQaPage } from "@/lib/products/source-qa";
import { sourceCropTargets, type SourceCropTarget } from "@/lib/products/source-qa-crop";
import type { SourceQaAiIssue, SourceQaAiReport } from "@/lib/products/source-qa-ai-contract";
import type { ProductTemplateDraft } from "@/lib/products/product-template-draft";
import type { SmartReviewedPricingSubgroups, StagedReviewedRowImage } from "@/lib/products/smart-product-row-images";
import { createClient } from "@/lib/supabase/client";

export function sourceQaAiIssueDetails(issue: SourceQaAiIssue) {
  return [["Code", issue.supplierModelCode], ["Page", issue.sourcePage], ["Source", issue.sourceEvidence], ["Source value", issue.sourceValue], ["JSON value", issue.jsonValue], ["JSON location", issue.jsonLocation]].filter((detail): detail is [string, string | number | boolean] => detail[1] !== null);
}

export function SourceQaAiIssueCard({ issue }: { issue: SourceQaAiIssue }) {
  return <article className="mt-2 rounded border border-zinc-200 bg-white p-2"><p className="font-semibold">{issue.severity.toUpperCase()} · {issue.confidence.toUpperCase()}</p><p className="mt-1 font-medium">{issue.type.replaceAll("_", " ")}</p>{sourceQaAiIssueDetails(issue).map(([label, value]) => <p key={label} className="mt-1 text-zinc-700"><span className="font-medium">{label}:</span> {String(value)}</p>)}<p className="mt-2">{issue.explanation}</p></article>;
}

export function SourceQaPanel({ draft, subgroups, onImageChange, images, onSourcePdfChange }: { draft: ProductTemplateDraft; subgroups?: SmartReviewedPricingSubgroups; images: Record<string, StagedReviewedRowImage>; onImageChange: (sourceKey: string, rowId: string, image: StagedReviewedRowImage) => void; onSourcePdfChange?: (sourcePdf?: { sourcePdfStoragePath?: string; sourcePdfFileName?: string }) => void }) {
  const [source, setSource] = useState<{ fileName: string; storagePath: string; pageCount: number } | null>(null); const [pages, setPages] = useState<SourceQaPage[]>([]); const [ignored, setIgnored] = useState<Set<string>>(new Set()); const [status, setStatus] = useState("Upload a manufacturer PDF to run advisory source coverage QA."); const [cropPage, setCropPage] = useState<number | null>(null); const [fixedTarget, setFixedTarget] = useState<SourceCropTarget | null>(null); const [cropSearch, setCropSearch] = useState(""); const [aiPending, setAiPending] = useState(false); const [aiError, setAiError] = useState<string | null>(null); const [aiReport, setAiReport] = useState<SourceQaAiReport | null>(null);
  const findings = useMemo(() => pages.length ? analyzeSourcePdf(source?.fileName ?? "source", pages, draft, ignored) : [], [draft, ignored, pages, source]); const missing = primarySourceQaFindings(findings); const targets = sourceCropTargets(draft, subgroups); const targetImageIds = new Set(targets.filter((target) => images[target.sourceKey + "\u0000" + target.rowId]).map((target) => target.id));
  useEffect(() => { const open = (event: Event) => { const detail = (event as CustomEvent<{ sourceKey: string; rowId: string }>).detail; const target = targets.find((item) => item.sourceKey === detail.sourceKey && item.rowId === detail.rowId); if (!source) { setStatus("Upload Source PDF in Source QA first."); return; } if (target) { setFixedTarget(target); setCropSearch(target.label.split(" — ")[0]); setCropPage(1); } }; window.addEventListener("source-qa-crop", open); return () => window.removeEventListener("source-qa-crop", open); }, [source, targets]);
  const upload = async (file: File) => { if (file.type !== "application/pdf") { setStatus("Select a PDF file."); return; } setStatus("Uploading and reading PDF…"); try { const path = "smart-source-qa/" + crypto.randomUUID() + "-" + file.name.replace(/[^a-z0-9.]+/gi, "-"); const { error } = await createClient().storage.from("product-source-files").upload(path, file, { contentType: "application/pdf", upsert: false }); if (error) throw error; const pdfjs = await import("pdfjs-dist/legacy/build/pdf.mjs"); pdfjs.GlobalWorkerOptions.workerSrc = new URL("pdfjs-dist/legacy/build/pdf.worker.mjs", import.meta.url).toString(); const document = await pdfjs.getDocument({ data: await file.arrayBuffer() }).promise; const extracted: SourceQaPage[] = []; for (let pageNumber = 1; pageNumber <= document.numPages; pageNumber += 1) { const content = await (await document.getPage(pageNumber)).getTextContent(); extracted.push({ pageNumber, text: content.items.map((item) => "str" in item ? item.str : "").join(" ") }); } setSource({ fileName: file.name, storagePath: path, pageCount: document.numPages }); onSourcePdfChange?.({ sourcePdfStoragePath: path, sourcePdfFileName: file.name }); setPages(extracted); setIgnored(new Set()); setAiError(null); setAiReport(null); setStatus("Source PDF ready: " + document.numPages + " pages."); } catch (error) { setStatus(error instanceof Error ? error.message : "PDF could not be read."); } };
  const runAiQa = async () => { if (!source || aiPending) return; setAiPending(true); setAiError(null); setAiReport(null); try { const result = await runSourceQaAi({ sourcePdfStoragePath: source.storagePath, sourcePdfFileName: source.fileName, draft }); if (result.ok) setAiReport(result.report); else setAiError(result.message); } catch { setAiError("AI Source QA could not be completed."); } finally { setAiPending(false); } };
  const assign = (selectedTargets: SourceCropTarget[], file: File) => { selectedTargets.forEach((target) => onImageChange(target.sourceKey, target.rowId, { file, previewUrl: URL.createObjectURL(file), sourceKey: target.sourceKey, sourceRowId: target.rowId })); setStatus("Image assigned to " + selectedTargets.length + " item" + (selectedTargets.length === 1 ? "." : "s.")); };
  return <section className="rounded-md border border-sky-200 bg-sky-50 p-3"><div className="flex flex-wrap justify-between gap-2"><div><b className="text-sm">Source QA</b><p className="text-xs">{status}</p></div><div className="flex gap-2"><button disabled={!source || aiPending} onClick={() => void runAiQa()} className="rounded border px-2 py-1 text-xs disabled:opacity-50">{aiPending ? "Running Source QA…" : "Run Source QA"}</button><button disabled={!source} onClick={() => { setFixedTarget(null); setCropSearch(""); setCropPage(1); }} className="rounded border px-2 py-1 text-xs disabled:opacity-50">Crop Images</button><label className="rounded border bg-white px-2 py-1 text-xs">Upload / Replace PDF<input className="hidden" type="file" accept="application/pdf" onChange={(event) => { const file = event.target.files?.[0]; event.target.value = ""; if (file) void upload(file); }} /></label></div></div>{aiError ? <p role="alert" className="mt-3 text-xs text-red-700">{aiError}</p> : null}{aiReport ? <div className="mt-3 text-xs"><b>AI Source QA: {aiReport.summary.issueCount} issue{aiReport.summary.issueCount === 1 ? "" : "s"}</b>{aiReport.issues.map((issue) => <SourceQaAiIssueCard key={issue.id} issue={issue} />)}</div> : null}{source ? <div className="mt-3 space-y-2 text-xs"><p><b>PDF: {source.pageCount} pages · Status: {sourceQaReviewStatus(findings) === "pass" ? "PASS" : "REVIEW NEEDED"}</b></p><p><b>Missing from JSON ({missing.length})</b></p>{missing.map((finding) => <div key={finding.normalizedCode} className="rounded border bg-white p-2"><b>{finding.sourceCode}</b> · PDF {finding.pageNumber}<p>{finding.section ?? "Source PDF"} · Not found in imported JSON</p><button onClick={() => { setFixedTarget(null); setCropSearch(finding.sourceCode); setCropPage(finding.pageNumber); }}>Crop Image</button><button className="ml-3" onClick={() => setIgnored((current) => new Set([...current, finding.normalizedCode]))}>Ignore</button></div>)}</div> : null}{source && cropPage ? <SourceQaCropViewer storagePath={source.storagePath} pageCount={source.pageCount} pages={pages} initialSearch={cropSearch} initialPage={cropPage} targets={targets} initialFixedTargetId={fixedTarget?.id} existingTargetIds={targetImageIds} onAssign={assign} onClose={() => { setCropPage(null); setFixedTarget(null); }} /> : null}</section>;
}
