"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { runSourceQaAi } from "@/app/products/templates/source-qa-actions";
import { SourceQaCropViewer } from "@/components/products/source-qa-crop-viewer";
import { analyzeSourcePdf, primarySourceQaFindings, sourceQaReviewStatus, type SourceQaPage } from "@/lib/products/source-qa";
import { sourceCropTargets, type SourceCropTarget } from "@/lib/products/source-qa-crop";
import type { SourceQaAiIssue, SourceQaAiReport } from "@/lib/products/source-qa-ai-contract";
import type { ProductTemplateDraft } from "@/lib/products/product-template-draft";
import type { OriginalImportedJsonSource } from "@/lib/products/original-imported-json-sources";
import type { SmartReviewedPricingSubgroups, StagedReviewedRowImage } from "@/lib/products/smart-product-row-images";
import { createClient } from "@/lib/supabase/client";

export function sourceQaAiIssueDetails(issue: SourceQaAiIssue) { return [["Code", issue.supplierModelCode], ["Page", issue.sourcePage], ["Source", issue.sourceEvidence], ["Source value", issue.sourceValue], ["JSON value", issue.jsonValue], ["JSON location", issue.jsonLocation]].filter((detail): detail is [string, string | number | boolean] => detail[1] !== null); }
const labels: Record<SourceQaAiIssue["type"], string> = { missing_source_row: "Missing source row", supplier_model_code_mismatch: "Code mismatch", price_value_mismatch: "Price mismatch", row_binding_mismatch: "Row/category mismatch", classification_mismatch: "Classification mismatch", excluded_scope_import: "Excluded item imported" };
const styles: Record<SourceQaAiIssue["severity"], string> = { critical: "bg-red-100 text-red-800", warning: "bg-amber-100 text-amber-800", info: "bg-sky-100 text-sky-800" };
function normalizedValue(value: string | number | boolean | null) { return value === null ? null : String(value).trim().toLocaleLowerCase(); }
export function sourceQaAiIssueLabel(issue: SourceQaAiIssue) { if (issue.type !== "price_value_mismatch" || normalizedValue(issue.sourceValue) !== normalizedValue(issue.jsonValue)) return labels[issue.type]; return /code|binding|row|categor/i.test(`${issue.explanation} ${issue.sourceEvidence ?? ""}`) ? "Row/code binding issue" : "Review item"; }
export function sourceQaAiDisplaySeverity(issue: SourceQaAiIssue) { return sourceQaAiIssueLabel(issue) === "Review item" ? "review" : issue.severity; }
function parent(location: string | null) { return location?.match(/^(.*(?:rows|items)\[\d+\])/)?.[1] ?? location ?? "unknown"; }
function groupKey(issue: SourceQaAiIssue) { return issue.supplierModelCode ? `code:${issue.supplierModelCode}|page:${issue.sourcePage ?? "unknown"}` : `page:${issue.sourcePage ?? "unknown"}|row:${parent(issue.jsonLocation)}`; }
function displayKey(issue: SourceQaAiIssue) { return [issue.type, issue.supplierModelCode, issue.sourcePage, issue.sourceValue, issue.jsonValue, issue.jsonLocation].map(String).join("\u0000"); }
const sortOrder: Record<SourceQaAiIssue["type"], number> = { supplier_model_code_mismatch: 1, price_value_mismatch: 2, row_binding_mismatch: 3, classification_mismatch: 4, missing_source_row: 5, excluded_scope_import: 6 };
export function sourceQaAiIssueGroups(issues: SourceQaAiIssue[]) { const groups = new Map<string, { key: string; code: string | null; page: number | null; issues: SourceQaAiIssue[] }>(); issues.forEach((issue) => { const key = groupKey(issue); const group = groups.get(key) ?? { key, code: issue.supplierModelCode, page: issue.sourcePage, issues: [] }; if (!group.issues.some((entry) => displayKey(entry) === displayKey(issue))) group.issues.push(issue); groups.set(key, group); }); return [...groups.values()].map((group) => ({ ...group, issues: group.issues.toSorted((left, right) => (sourceQaAiIssueLabel(left) === "Review item" || sourceQaAiIssueLabel(left) === "Row/code binding issue" ? 7 : sortOrder[left.type]) - (sourceQaAiIssueLabel(right) === "Review item" || sourceQaAiIssueLabel(right) === "Row/code binding issue" ? 7 : sortOrder[right.type])) })); }
export function sourceQaAiSummary(issues: SourceQaAiIssue[]) { const groups = sourceQaAiIssueGroups(issues); const rendered = groups.flatMap((group) => group.issues); const counts = { critical: 0, warning: 0, info: 0 }; rendered.forEach((issue) => { const severity = sourceQaAiDisplaySeverity(issue); if (severity !== "review") counts[severity] += 1; }); return { groups, findings: rendered.length, counts, status: counts.critical ? "REVIEW REQUIRED" : counts.warning ? "REVIEW" : "PASS" }; }
function IssueRow({ issue }: { issue: SourceQaAiIssue }) { const severity = sourceQaAiDisplaySeverity(issue); return <div className="grid gap-2 border-t border-zinc-100 py-2 text-xs sm:grid-cols-[minmax(9rem,1fr)_minmax(7rem,1fr)_minmax(7rem,1fr)_auto]"><div><p className="font-medium">{sourceQaAiIssueLabel(issue)}</p><p className="text-zinc-500">{issue.confidence} confidence</p></div><div><span className="sm:hidden">PDF / Source: </span>{issue.sourceValue ?? "—"}</div><div><span className="sm:hidden">JSON: </span>{issue.jsonValue ?? "—"}</div><span className={`w-fit rounded px-2 py-0.5 font-semibold ${severity === "review" ? "bg-zinc-100 text-zinc-700" : styles[severity]}`}>{severity}</span><details className="sm:col-span-4"><summary className="cursor-pointer text-zinc-600">Show details</summary><div className="mt-2 space-y-1 rounded bg-zinc-50 p-2"><p><b>Source evidence:</b> {issue.sourceEvidence ?? "—"}</p><p><b>JSON location:</b> {issue.jsonLocation ?? "—"}</p><p><b>Explanation:</b> {issue.explanation}</p></div></details></div>; }
export function SourceQaAiIssueGroups({ issues }: { issues: SourceQaAiIssue[] }) { const summary = sourceQaAiSummary(issues); return <div className="mt-3 text-xs"><div className="flex flex-wrap gap-x-3 gap-y-1 rounded border border-sky-200 bg-white p-2"><b>AI Verification: {summary.status}</b><span>{summary.groups.length} affected item{summary.groups.length === 1 ? "" : "s"}</span><span>{summary.findings} finding{summary.findings === 1 ? "" : "s"}</span><span className="text-red-800">Critical {summary.counts.critical}</span><span className="text-amber-800">Warning {summary.counts.warning}</span><span className="text-sky-800">Info {summary.counts.info}</span></div>{summary.groups.map((group) => <section key={group.key} className="mt-2 rounded border border-zinc-200 bg-white p-2"><p className="font-semibold">{group.code ?? "Uncoded item"}{group.page ? ` · Page ${group.page}` : " · Page unavailable"}</p><div className="mt-1 hidden grid-cols-[minmax(9rem,1fr)_minmax(7rem,1fr)_minmax(7rem,1fr)_auto] gap-2 text-zinc-500 sm:grid"><span>Type</span><span>PDF / Source</span><span>JSON</span><span>Severity</span></div>{group.issues.map((issue) => <IssueRow key={displayKey(issue)} issue={issue} />)}</section>)}</div>; }
export function SourceQaPanel({ draft, originalImportedJsonSources, subgroups, onImageChange, images, onSourcePdfChange, onSuppliedPagesChange }: { draft: ProductTemplateDraft; originalImportedJsonSources: OriginalImportedJsonSource[]; subgroups?: SmartReviewedPricingSubgroups; images: Record<string, StagedReviewedRowImage>; onImageChange: (sourceKey: string, rowId: string, image: StagedReviewedRowImage) => void; onSourcePdfChange?: (sourcePdf?: { sourcePdfStoragePath?: string; sourcePdfFileName?: string }) => void; onSuppliedPagesChange?: (pageNumbers: number[] | null) => void }) {
  const [source, setSource] = useState<{ fileName: string; storagePath: string; pageCount: number } | null>(null); const [pages, setPages] = useState<SourceQaPage[]>([]); const [ignored, setIgnored] = useState<Set<string>>(new Set()); const [status, setStatus] = useState("Upload a manufacturer PDF to run advisory source coverage QA."); const [cropPage, setCropPage] = useState<number | null>(null); const [fixedTarget, setFixedTarget] = useState<SourceCropTarget | null>(null); const [cropSearch, setCropSearch] = useState(""); const [aiPending, setAiPending] = useState(false); const [aiError, setAiError] = useState<string | null>(null); const [aiReport, setAiReport] = useState<SourceQaAiReport | null>(null);
  // Collapsed by default once QA results exist (source PDF loaded); expanded before that so Run Source QA stays visible.
  // A manual Show/Hide toggle (or an earlier auto-collapse) permanently disables further automatic collapsing
  // via the ref, so the panel never unexpectedly closes on the user while they are working inside it.
  const [expanded, setExpanded] = useState(true); const autoCollapsed = useRef(false);
  const toggleExpanded = () => { setExpanded((current) => !current); autoCollapsed.current = true; };
  const findings = useMemo(() => pages.length ? analyzeSourcePdf(source?.fileName ?? "source", pages, draft, ignored) : [], [draft, ignored, pages, source]); const missing = primarySourceQaFindings(findings); const unsuppliedReferences = findings.filter((finding) => finding.status === "referenced_unsupplied_page"); const targets = sourceCropTargets(draft, subgroups); const targetImageIds = new Set(targets.filter((target) => images[target.sourceKey + "\u0000" + target.rowId]).map((target) => target.id));
  useEffect(() => { const open = (event: Event) => { const detail = (event as CustomEvent<{ sourceKey: string; rowId: string }>).detail; const target = targets.find((item) => item.sourceKey === detail.sourceKey && item.rowId === detail.rowId); if (!source) { setStatus("Upload Source PDF in Source QA first."); return; } if (target) { setFixedTarget(target); setCropSearch(target.label.split(" — ")[0]); setCropPage(1); } }; window.addEventListener("source-qa-crop", open); return () => window.removeEventListener("source-qa-crop", open); }, [source, targets]);
  const upload = async (file: File) => { if (file.type !== "application/pdf") { setStatus("Select a PDF file."); return; } setStatus("Uploading and reading PDF…"); try { const path = "smart-source-qa/" + crypto.randomUUID() + "-" + file.name.replace(/[^a-z0-9.]+/gi, "-"); const { error } = await createClient().storage.from("product-source-files").upload(path, file, { contentType: "application/pdf", upsert: false }); if (error) throw error; const pdfjs = await import("pdfjs-dist/legacy/build/pdf.mjs"); pdfjs.GlobalWorkerOptions.workerSrc = new URL("pdfjs-dist/legacy/build/pdf.worker.mjs", import.meta.url).toString(); const document = await pdfjs.getDocument({ data: await file.arrayBuffer() }).promise; const extracted: SourceQaPage[] = []; for (let pageNumber = 1; pageNumber <= document.numPages; pageNumber += 1) { const content = await (await document.getPage(pageNumber)).getTextContent(); extracted.push({ pageNumber, text: content.items.map((item) => "str" in item ? item.str : "").join(" ") }); } setSource({ fileName: file.name, storagePath: path, pageCount: document.numPages }); onSourcePdfChange?.({ sourcePdfStoragePath: path, sourcePdfFileName: file.name }); setPages(extracted); onSuppliedPagesChange?.(extracted.map((page) => page.pageNumber)); setIgnored(new Set()); setAiError(null); setAiReport(null); setStatus("Source PDF ready: " + document.numPages + " pages."); if (!autoCollapsed.current) { autoCollapsed.current = true; setExpanded(false); } } catch (error) { setStatus(error instanceof Error ? error.message : "PDF could not be read."); } };
  const runAiQa = async () => { if (!source || aiPending) return; setAiPending(true); setAiError(null); setAiReport(null); try { const result = await runSourceQaAi({ sourcePdfStoragePath: source.storagePath, sourcePdfFileName: source.fileName, originalImportedJsonSources, draft }); if (result.ok) setAiReport(result.report); else setAiError(result.message); } catch { setAiError("AI Source QA could not be completed."); } finally { setAiPending(false); } };
  const assign = (selectedTargets: SourceCropTarget[], file: File) => { selectedTargets.forEach((target) => onImageChange(target.sourceKey, target.rowId, { file, previewUrl: URL.createObjectURL(file), sourceKey: target.sourceKey, sourceRowId: target.rowId })); setStatus("Image assigned to " + selectedTargets.length + " item" + (selectedTargets.length === 1 ? "." : "s.")); };
  const compactSummary = source ? `PDF: ${source.pageCount} pages · Status: ${sourceQaReviewStatus(findings) === "pass" ? "PASS" : "REVIEW NEEDED"} · Missing: ${missing.length}` : status;
  return <section className="rounded-md border border-sky-200 bg-sky-50 p-3"><div className="flex flex-wrap justify-between gap-2"><div><b className="text-sm">Source QA</b><p className="text-xs">{!expanded ? compactSummary : status}</p></div><div className="flex flex-wrap gap-2">{expanded ? <><button disabled={!source || aiPending} onClick={() => void runAiQa()} className="rounded border px-2 py-1 text-xs disabled:opacity-50">{aiPending ? "Running Source QA…" : "Run Source QA"}</button><button disabled={!source} onClick={() => { setFixedTarget(null); setCropSearch(""); setCropPage(1); }} className="rounded border px-2 py-1 text-xs disabled:opacity-50">Crop Images</button><label className="rounded border bg-white px-2 py-1 text-xs">Upload / Replace PDF<input className="hidden" type="file" accept="application/pdf" onChange={(event) => { const file = event.target.files?.[0]; event.target.value = ""; if (file) void upload(file); }} /></label></> : null}<button type="button" aria-expanded={expanded} onClick={toggleExpanded} className="rounded border border-zinc-300 bg-white px-2 py-1 text-xs font-semibold text-emerald-900">{expanded ? "Hide" : "Show"}</button></div></div>{expanded ? <>{aiError ? <p role="alert" className="mt-3 text-xs text-red-700">{aiError}</p> : null}{aiReport ? <SourceQaAiIssueGroups issues={aiReport.issues} /> : null}{source ? <div className="mt-3 space-y-2 text-xs"><p><b>PDF: {source.pageCount} pages · Status: {sourceQaReviewStatus(findings) === "pass" ? "PASS" : "REVIEW NEEDED"}</b></p><p><b>Missing from supplied pages ({missing.length})</b></p>{missing.map((finding) => <div key={finding.normalizedCode} className="rounded border bg-white p-2"><b>{finding.sourceCode}</b> · PDF {finding.pageNumber}<p>{finding.section ?? "Source PDF"} · Not found in imported JSON</p><button onClick={() => { setFixedTarget(null); setCropSearch(finding.sourceCode); setCropPage(finding.pageNumber); }}>Crop Image</button><button className="ml-3" onClick={() => setIgnored((current) => new Set([...current, finding.normalizedCode]))}>Ignore</button></div>)}<p><b>Referenced pages not supplied ({unsuppliedReferences.length})</b></p>{unsuppliedReferences.map((finding) => <div key={finding.normalizedCode} className="rounded border border-amber-200 bg-amber-50 p-2"><b>{finding.sourceCode}</b> · referenced on PDF {finding.pageNumber}<p>{finding.section ?? "Source PDF"} · Supplemental source pages are needed before their rows can be checked.</p></div>)}</div> : null}</> : null}{source && cropPage ? <SourceQaCropViewer storagePath={source.storagePath} pageCount={source.pageCount} pages={pages} initialSearch={cropSearch} initialPage={cropPage} targets={targets} initialFixedTargetId={fixedTarget?.id} existingTargetIds={targetImageIds} onAssign={assign} onClose={() => { setCropPage(null); setFixedTarget(null); }} /> : null}</section>;
}
