"use client";

import { useEffect, useState } from "react";
import { searchSupplierSourceInspector, supplierSourceInspectorDetails } from "@/app/products/price-updates/supplier-sources/actions";
import type { SupplierSourceInspectorDetail, SupplierSourceInspectorRow } from "@/lib/products/supplier-price-repository";

const button = "inline-flex h-8 items-center justify-center rounded-md border border-zinc-200 bg-white px-3 text-xs font-semibold text-zinc-700 transition hover:border-zinc-300 hover:bg-zinc-50";
const money = (row: SupplierSourceInspectorRow) => row.price === null ? "Invalid" : `${row.currency} ${row.price}`;
const tier = (row: SupplierSourceInspectorRow) => row.dimension === "finish_set" ? "Finish-specific" : row.dimension || "—";
const warning = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());

export function SupplierSourceInspector({ sourceId, brandName, sourceTitle }: { sourceId: string; brandName: string; sourceTitle: string }) {
  const [open, setOpen] = useState(false); const [query, setQuery] = useState(""); const [rows, setRows] = useState<SupplierSourceInspectorRow[]>([]); const [detail, setDetail] = useState<SupplierSourceInspectorDetail | null>(null);
  const [offset, setOffset] = useState(0); const [hasMore, setHasMore] = useState(false); const [exactCount, setExactCount] = useState(0); const [searched, setSearched] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const title = sourceTitle.toLowerCase().startsWith(brandName.toLowerCase()) ? sourceTitle : `${brandName} — ${sourceTitle}`;
  async function search(value = query, nextOffset = 0) { setBusy(true); setMessage(""); setDetail(null); try { const result = await searchSupplierSourceInspector(sourceId, value, nextOffset); setRows(result.rows); setOffset(nextOffset); setHasMore(result.hasMore); setExactCount(result.exactCount); setSearched(Boolean(value.trim())); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not load extracted data."); } finally { setBusy(false); } }
  async function showDetails(key: string) { setBusy(true); try { setDetail(await supplierSourceInspectorDetails(sourceId, key)); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not load source details."); } finally { setBusy(false); } }
  function clear() { setQuery(""); setRows([]); setDetail(null); setOffset(0); setHasMore(false); setExactCount(0); setSearched(false); setMessage(""); }
  useEffect(() => { const source = (event: Event) => { const code = (event as CustomEvent<{ code?: string }>).detail?.code ?? ""; setQuery(code); setOpen(true); void search(code); }; const escape = (event: KeyboardEvent) => { if (event.key === "Escape") setOpen(false); }; window.addEventListener("supplier-source-inspector", source); window.addEventListener("keydown", escape); return () => { window.removeEventListener("supplier-source-inspector", source); window.removeEventListener("keydown", escape); }; });
  return <><button type="button" className={button} onClick={() => { setOpen(true); void search(); }}>View extracted data</button>{open ? <div role="dialog" aria-modal="true" aria-labelledby="supplier-source-inspector-title" className="fixed inset-0 z-50 flex items-start justify-center bg-zinc-950/30 p-4 sm:items-center">
    <section className="flex max-h-[calc(100vh-2rem)] w-full max-w-7xl flex-col overflow-hidden rounded-lg border border-zinc-200 bg-white shadow-xl">
      <div className="sticky top-0 z-10 border-b border-zinc-200 bg-white p-4"><div className="flex items-start justify-between gap-3"><div><h2 id="supplier-source-inspector-title" className="text-lg font-semibold">Extracted Supplier Data</h2><p className="text-sm font-medium">{title}</p><p className="mt-1 text-xs text-zinc-500">Search what ProjectWorkflow extracted from this price list.</p></div><button type="button" aria-label="Close extracted Supplier data inspector" className={button} onClick={() => setOpen(false)}>× Close</button></div>
        <form className="mt-4 flex flex-wrap items-end gap-2" onSubmit={(event) => { event.preventDefault(); void search(); }}><label className="grid gap-1 text-xs font-semibold">Search code<input aria-label="Search code" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search article or Supplier code" className="h-9 w-72 rounded-md border border-zinc-300 px-3 text-sm font-normal" /></label><button className="h-9 rounded-md bg-emerald-900 px-4 text-sm font-semibold text-white" disabled={busy}>Search</button><button type="button" className={button} disabled={busy} onClick={clear}>Clear</button><p className="basis-full text-xs text-zinc-500">Examples: 1AG 207, 1AG207, 111071, 1AJ M33</p></form></div>
      <div className="overflow-y-auto p-4">{message ? <p role="alert" className="rounded border border-amber-200 bg-amber-50 p-2 text-sm">{message}</p> : null}{searched && !busy && rows.length ? <><p className="mt-3 text-sm font-medium">{exactCount === 1 ? "1 exact code match" : `${rows.length} extracted identities found`}</p><p className="mt-2 rounded border border-sky-200 bg-sky-50 p-2 text-sm">This code exists in the imported Supplier source. If the Product is still shown as Missing or Needs attention, review its matching details.</p></> : null}{searched && !busy && !rows.length ? <p className="mt-3 rounded border border-zinc-200 bg-zinc-50 p-3 text-sm">No extracted Supplier identity was found for this code.</p> : null}
        <div className="mt-3 overflow-x-auto"><table className="min-w-full divide-y divide-zinc-200 text-sm"><thead className="sticky top-0 bg-zinc-50"><tr className="text-left">{["Article code", "Price", "Currency", "Price field", "Dimension", "Finishes", "Source rows", "Status", "Action"].map((name) => <th key={name} className="px-3 py-2 text-xs font-semibold uppercase tracking-wide text-zinc-500">{name}</th>)}</tr></thead><tbody className="divide-y divide-zinc-100">{rows.map((row) => <tr key={row.key}><td className="px-3 py-2 font-mono font-semibold">{row.code}</td><td className="px-3 py-2">{money(row)}</td><td className="px-3 py-2">{row.currency}</td><td className="px-3 py-2">{row.priceField}</td><td className="px-3 py-2">{tier(row)}</td><td className="px-3 py-2">{row.finishes.length ? `${row.finishes.length} finishes` : "—"}</td><td className="px-3 py-2">{row.sourceRowCount} rows</td><td className="px-3 py-2">{row.warnings.length ? "Source warning" : row.multiplePriceIdentities ? "Multiple price identities" : "Extracted"}</td><td className="px-3 py-2"><button type="button" className={button} disabled={busy} onClick={() => void showDetails(row.key)}>View details</button></td></tr>)}</tbody></table></div>
        <div className="mt-3 flex justify-between"><button type="button" className={button} disabled={busy || offset === 0} onClick={() => void search(query, Math.max(0, offset - 50))}>Previous</button><span className="pt-2 text-xs text-zinc-500">{busy ? "Loading…" : `Showing ${rows.length} results`}</span><button type="button" className={button} disabled={busy || !hasMore} onClick={() => void search(query, offset + 50)}>Next</button></div>
        {detail ? <section className="mt-4 rounded border border-zinc-200 bg-zinc-50 p-3"><div className="flex justify-between"><h3 className="font-semibold">{detail.code} details</h3><button type="button" className={button} onClick={() => setDetail(null)}>Close details</button></div><dl className="mt-2 grid gap-2 text-sm sm:grid-cols-3">{[["Article code", detail.code], ["Supplier price", money(detail)], ["Currency", detail.currency], ["Price field", detail.priceField], ["Dimension / tier", tier(detail)], ["Source rows", detail.sourceRowCount]].map(([label, value]) => <div key={label}><dt className="text-zinc-500">{label}</dt><dd>{value}</dd></div>)}</dl>{detail.finishes.length ? <details className="mt-3"><summary>{detail.finishes.length} finishes</summary><p className="font-mono text-xs">{detail.finishes.join(", ")}</p></details> : null}{detail.fullCodes.length ? <p className="mt-2 text-sm"><strong>Full Supplier codes:</strong> {detail.fullCodes.join(", ")}</p> : null}{detail.warnings.length ? <p className="mt-2 text-sm text-amber-900"><strong>Source warning:</strong> {detail.warnings.map(warning).join("; ")}</p> : null}<div className="mt-3"><h4 className="font-semibold">Source evidence</h4>{detail.evidence.map((row) => <div key={`${row.sheet}:${row.sourceRowNumber}`} className="mt-1 border-t border-zinc-200 pt-1 text-sm"><strong>{row.sheet}, row {row.sourceRowNumber}</strong>{row.fullCode ? <div>Full code: {row.fullCode}</div> : null}{row.articleCode ? <div>Article code: {row.articleCode}</div> : null}{row.description ? <div>Description: {row.description}</div> : null}{row.finishCode ? <div>Finish code: {row.finishCode}</div> : null}{row.categoryLabel ? <div>Category / tier: {row.categoryLabel}</div> : null}{row.dimensionLabel ? <div>Dimension: {row.dimensionLabel}</div> : null}{row.rawPrice ? <div>Raw price: {row.rawPrice}</div> : null}<div>Price: {row.currency} {row.price ?? "Invalid"}</div></div>)}{detail.moreEvidence ? <p className="mt-2 text-xs text-zinc-500">+ {detail.moreEvidence} more rows</p> : null}</div></section> : null}
      </div>
    </section>
  </div> : null}</>;
}
